# Generated by Django 4.1.4 on 2023-01-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coment',
            old_name='owner',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='coment',
            old_name='comented_post',
            new_name='post',
        ),
        migrations.AddField(
            model_name='coment',
            name='type',
            field=models.CharField(default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='dislike',
            name='type',
            field=models.CharField(default='d', max_length=1),
        ),
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.CharField(default='l', max_length=1),
        ),
    ]
