# Generated by Django 4.1.4 on 2022-12-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dislikes',
            new_name='reactions',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
