# Generated by Django 4.1.4 on 2023-01-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_dislikes_post_reactions_remove_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coment',
            options={'ordering': ['-added']},
        ),
        migrations.RenameField(
            model_name='coment',
            old_name='addes',
            new_name='added',
        ),
    ]
