# Generated by Django 4.1.4 on 2023-01-01 15:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_iterractions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Iterractions',
            new_name='Interractions',
        ),
    ]
