# Generated by Django 4.1.4 on 2023-01-01 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rename_iterractions_interractions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dislike',
            options={'ordering': ['-added']},
        ),
        migrations.AlterModelOptions(
            name='interractions',
            options={'ordering': ['-added']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-added']},
        ),
        migrations.RenameField(
            model_name='dislike',
            old_name='disliked',
            new_name='added',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='liked',
            new_name='added',
        ),
        migrations.AddField(
            model_name='interractions',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
