# Generated by Django 4.1.4 on 2023-01-02 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0002_alter_message_options_remove_messagesroom_owners_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesroom',
            name='owner1',
        ),
        migrations.RemoveField(
            model_name='messagesroom',
            name='owner2',
        ),
        migrations.AddField(
            model_name='messagesroom',
            name='owner1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagesroom',
            name='owner2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner2', to=settings.AUTH_USER_MODEL),
        ),
    ]
