# Generated by Django 4.1.4 on 2023-01-04 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_messagesroom_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdeleteask',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='message.messagesroom'),
        ),
    ]
