# Generated by Django 4.1.4 on 2023-01-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_messagesroom_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesroom',
            name='deleted1',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='messagesroom',
            name='deleted2',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
