# Generated by Django 4.1.4 on 2022-12-26 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='localstaff',
            name='local_ovners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ovners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localstaff',
            name='local_workers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locals',
            name='local_street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.street'),
        ),
        migrations.AddField(
            model_name='localproducts',
            name='product_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.locals'),
        ),
    ]
