# Generated by Django 4.1.4 on 2023-01-17 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='placetovisit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placefavourite',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.locals'),
        ),
        migrations.AddField(
            model_name='placefavourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locals',
            name='local_street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.street'),
        ),
        migrations.AddField(
            model_name='locals',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localrating',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.locals'),
        ),
        migrations.AddField(
            model_name='localrating',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localproducts',
            name='product_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.locals'),
        ),
        migrations.AddField(
            model_name='localproductrating',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localproductrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.localproducts'),
        ),
    ]
