# Generated by Django 4.1.4 on 2022-12-26 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localstaff',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='localstaff',
            name='local_ovners',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localstaff',
            name='local_workers',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
