# Generated by Django 4.1.4 on 2023-01-03 09:16

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_localrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='locals',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=places.models.get_profile_image_filepath),
        ),
    ]
