# Generated by Django 4.1.4 on 2023-01-03 18:11

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_locals_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='localproducts',
            name='product_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=places.models.get_profile_product_image_filepath),
        ),
    ]
