import requests

# print("--------------------------------------------------------")

# endpoint = "http://127.0.0.1:8000/api/posts/"
# get_respone = requests.get(endpoint)
# print(get_respone.json())

# print("--------------------------------------------------------")

# endpoint = "http://127.0.0.1:8000/api/locals/"
# get_respone = requests.get(endpoint)
# print(get_respone.json())

# print("--------------------------------------------------------")

# endpoint = "http://127.0.0.1:8000/api/local/products/"
# get_respone = requests.get(endpoint)
# print(get_respone.json())

# print("--------------------------------------------------------")

# print("--------------------------------------------------------")

# endpoint = "http://127.0.0.1:8000/api/local/products/26/"
# get_respone = requests.get(endpoint)
# print(get_respone.json())

# print("--------------------------------------------------------")

sample = '''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut gravida lectus. Sed elementum tempor aliquet. Phasellus malesuada vitae ligula nec ultricies. Donec viverra eros elit, vel semper odio molestie id. Nulla sed feugiat risus, vel eleifend tortor. Morbi faucibus eu nibh ut tempor. Proin interdum sed erat nec porta. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque arcu nisi, pellentesque non congue quis, ultrices et urna. Curabitur gravida imperdiet placerat. Sed eu auctor odio. Integer quis sem posuere, efficitur tellus nec, eleifend lacus. Duis vel feugiat mauris, euismod ullamcorper dui. Morbi id pretium mauris, rhoncus molestie augue.

Maecenas aliquet faucibus nibh, eu semper risus condimentum vitae. Donec imperdiet elit sit amet quam fringilla, et fringilla turpis placerat. Proin iaculis ut justo et blandit. Sed commodo facilisis magna at scelerisque. Nulla a felis sollicitudin, lobortis leo sit amet, semper mi. Suspendisse eget lacus in nulla varius posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus fermentum condimentum risus. Suspendisse ante orci, vestibulum vel nunc sed, imperdiet molestie ante. Fusce ultricies porta sem maximus facilisis. Praesent sit amet quam dolor. Cras faucibus dolor nibh, quis venenatis nibh mattis ut. Pellentesque viverra urna nulla, non tincidunt felis interdum vitae. Proin sollicitudin volutpat lacus, vitae finibus arcu iaculis non. Nullam consectetur lorem massa, non malesuada diam volutpat a.

Aenean vel venenatis lectus, eu faucibus justo. Cras hendrerit placerat felis sed mattis. Morbi semper euismod varius. Suspendisse accumsan nisl sit amet semper dignissim. Aliquam hendrerit ante vitae erat varius, ac pharetra elit interdum. Duis commodo metus ut risus interdum, et rhoncus dui consequat. Cras luctus neque eu tellus pharetra imperdiet. Vestibulum commodo viverra libero sit amet lacinia. Sed sed ornare nisl. Cras suscipit ante sapien, sit amet bibendum nisi laoreet a. Mauris at ullamcorper turpis. Aliquam imperdiet ipsum at massa imperdiet, ut varius nibh aliquam. In consectetur quis ante eu scelerisque. Curabitur scelerisque laoreet euismod. Nulla facilisi.

Donec in auctor massa. Nunc sit amet odio semper, semper magna ac, condimentum ante. Curabitur ullamcorper eros ut turpis lacinia posuere. Ut feugiat, diam eget condimentum congue, felis risus fringilla lacus, sed finibus nibh ipsum tincidunt elit. Proin condimentum et magna eu molestie. Pellentesque eu urna et felis iaculis ultricies et a metus. In hac habitasse platea dictumst.

Maecenas pulvinar augue sit amet orci ultrices sagittis. Nulla facilisi. Integer elementum sit amet tellus quis malesuada. Duis nulla felis, ornare et vehicula eget, rutrum at ipsum. Integer lacinia enim elit, a pretium metus finibus ac. Nunc fringilla diam lectus, sodales imperdiet urna fringilla porta. Vivamus tempor, nibh eget scelerisque maximus, mauris arcu facilisis nibh, eu accumsan felis tortor sit amet elit. Vestibulum ac risus ullamcorper, fermentum turpis eu, ultricies sem. Vivamus fermentum enim quis ullamcorper eleifend. Nullam cursus quis libero ornare ullamcorper. Pellentesque ac vestibulum dui, non viverra velit. Phasellus tempus nulla sit amet dui posuere fringilla vitae ac orci. Pellentesque vestibulum, velit vel ornare accumsan, lectus lorem iaculis ipsum, ac fringilla lorem enim quis turpis.

Integer lacinia turpis nibh, quis aliquam diam fermentum et. Vivamus suscipit auctor neque, nec tempus enim. Etiam vel ultricies arcu. Sed commodo mattis porta. Donec tempus ante sed varius commodo. Fusce rutrum odio vel pretium malesuada. Suspendisse rhoncus tortor vel nunc accumsan convallis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur eget lacus ultrices, scelerisque nunc quis, sodales magna. Donec et convallis ante. Nunc semper augue at rhoncus scelerisque. Curabitur pellentesque finibus ipsum, id interdum orci tincidunt vitae. Morbi pretium eu lectus eu rutrum.

Quisque egestas, augue quis porttitor eleifend, est ante ullamcorper tellus, quis euismod mi quam in elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam eget nunc sit amet libero pulvinar dictum. Vivamus porttitor sapien quam, a laoreet sem bibendum eu. Vestibulum at dolor tempor dui placerat volutpat eu eu diam. Pellentesque placerat in orci sit amet ornare. Morbi hendrerit porttitor congue. Vestibulum sit amet sapien magna. Cras et orci nisi. Duis luctus libero eros, in auctor nulla vestibulum et. Nunc sed fermentum tellus. Vivamus sed ullamcorper ligula, vitae venenatis orci. Cras ultricies mi in augue vehicula dapibus. Cras quis arcu felis. Donec vehicula, velit sed malesuada finibus, tortor leo pulvinar ipsum, eu interdum arcu nulla nec velit.

Etiam vulputate augue ut consequat tristique. Nam finibus risus eget aliquam convallis. Donec et tempor metus, sed vehicula elit. Vestibulum lobortis quis tortor non aliquet. Aenean ac bibendum orci. Aenean ligula nisl, tincidunt placerat venenatis id, luctus id quam. Aliquam interdum, erat at bibendum efficitur, urna risus lobortis est, vitae hendrerit magna nulla eu nisl. Nulla molestie odio urna, a ornare dolor tincidunt sed. Suspendisse non tellus a augue fringilla dictum. Integer eu tempus mauris, id hendrerit felis. Cras imperdiet dictum mi eu interdum. Phasellus et ipsum arcu. Suspendisse pharetra feugiat pretium.

In ut turpis quam. Vivamus ut nibh ut tellus placerat scelerisque. Nulla felis dui, cursus sit amet libero et, maximus venenatis nisi. Aenean gravida mattis diam, vitae accumsan leo. Suspendisse at ante laoreet, imperdiet massa sit amet, maximus odio. Proin pulvinar leo at metus posuere, a rhoncus arcu ornare. Sed non molestie augue. Aliquam a dui laoreet, ullamcorper dolor id, ultricies justo. Cras porttitor ac ex ut accumsan. Aenean gravida dictum congue. Etiam quis auctor purus. Ut ac arcu et ex laoreet congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Morbi magna neque, semper eget porttitor at, venenatis ac nibh. Aliquam lobortis magna vel eleifend lobortis. Donec sed lacus gravida, consectetur nisi vitae, imperdiet urna. Donec consequat nibh at sapien dignissim, vel bibendum odio fringilla. Etiam elit ipsum, dignissim vitae nisl malesuada, pellentesque malesuada nisi. Proin consectetur sapien volutpat, dapibus turpis a, sodales dui. Duis sed euismod diam, sed blandit turpis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque quis risus vel leo feugiat condimentum ac ac est. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Duis lacinia viverra ultrices. Curabitur vulputate nec mauris suscipit efficitur. Proin elit tortor, interdum et nibh ut, fringilla rutrum ipsum. Sed tincidunt nibh purus, quis condimentum purus aliquet rutrum. Vivamus tortor mauris, pellentesque sit amet eleifend nec, pharetra vel tortor. Curabitur quis ante vitae nisi facilisis consequat rhoncus eu urna. Nulla facilisi. Aenean velit ante, porta in nisi eget, sollicitudin congue metus. Proin ex metus, sollicitudin ut mi a, faucibus pharetra metus. Integer fringilla, augue eu faucibus efficitur, turpis lorem ornare massa, iaculis sagittis diam arcu nec lacus. Pellentesque euismod varius justo rhoncus viverra. Fusce sed dapibus massa. Nam commodo velit ut euismod egestas. Ut lobortis congue nulla.

In pharetra pellentesque risus, sit amet eleifend risus accumsan id. Donec sit amet eros eget nunc aliquam placerat. Maecenas at ligula vel eros imperdiet bibendum. Mauris ac pulvinar lorem. Nunc eu orci purus. Quisque sodales vehicula massa, vel consequat justo. Fusce id lobortis orci. Donec a posuere turpis. Sed volutpat felis varius mi varius aliquam. Proin id lacinia erat. Suspendisse placerat arcu sapien, ac sagittis nibh hendrerit aliquet. Nullam purus velit, dictum eu venenatis sed, commodo a neque. Sed accumsan ipsum ultrices nunc efficitur, a eleifend odio lobortis.

Sed posuere neque id tempor tincidunt. Sed efficitur, dui at pellentesque bibendum, quam sapien porta mauris, vitae placerat urna quam a augue. Cras hendrerit tellus lobortis, pharetra elit quis, eleifend justo. Donec euismod eros non tellus sodales, eu pellentesque mi venenatis. Donec lorem erat, posuere et leo ac, hendrerit facilisis elit. Integer eget laoreet nisi. Donec non sollicitudin nisl. Pellentesque quis consectetur ipsum. Aliquam erat volutpat. Cras a mauris mi. Curabitur blandit odio at est vehicula cursus. Donec massa tortor, volutpat nec lobortis quis, vulputate at mi.

Nunc vulputate arcu ac eleifend venenatis. Nam congue metus quis auctor faucibus. Cras consectetur lacinia lectus, a egestas justo sollicitudin tincidunt. Nullam et laoreet tortor, eu fermentum orci. In ultrices orci magna, quis hendrerit mauris tristique at. Aliquam erat volutpat. Sed odio metus, cursus et magna et, sagittis rutrum lectus. Cras non lacinia arcu. Cras ut turpis interdum, suscipit dolor eget, pretium orci. Vivamus imperdiet tellus at ultricies feugiat. Curabitur euismod est ac ante vestibulum sodales quis in ex. Vivamus consectetur dolor id ornare dictum. Ut vehicula quam sit amet mi ultrices, ac tincidunt tortor laoreet.

Duis vitae egestas sem. Curabitur pharetra elit vitae massa tincidunt, et maximus ipsum ultrices. Etiam ligula neque, imperdiet non gravida lacinia, sollicitudin eget eros. Suspendisse porta erat sit amet ipsum posuere molestie. Praesent dapibus sem nibh, lacinia egestas orci vestibulum sit amet. Nulla facilisi. Duis tellus lectus, egestas ut ligula nec, faucibus dignissim tortor. Morbi nec dui vitae risus consectetur molestie. Phasellus eu eros mauris. Vestibulum nec ultricies ligula, in rutrum ligula.

Aenean facilisis augue at nunc congue, quis ultrices massa lobortis. Suspendisse potenti. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam suscipit mattis luctus. Vivamus massa nisl, congue ut lectus quis, imperdiet convallis ante. Aliquam pellentesque orci id leo faucibus, a malesuada augue tincidunt. Nunc rhoncus tortor quis augue porttitor, id vulputate magna lobortis. Donec viverra egestas placerat.

Duis ut semper ante. Integer metus risus, mollis et lacinia ut, auctor vel nulla. In posuere sagittis tortor ac lobortis. Donec ultrices est vel dui ullamcorper laoreet. Proin condimentum vestibulum ipsum, aliquet suscipit metus euismod a. Sed ullamcorper massa sed purus interdum, eget sodales ipsum gravida. Quisque vel posuere velit. Cras convallis, leo vitae tempor condimentum, eros est pretium tellus, a dignissim purus felis eget nibh. Pellentesque maximus laoreet volutpat. Nam dapibus libero non justo aliquet sagittis.

Cras luctus porta nunc, a tempus eros hendrerit nec. In ac massa maximus, accumsan metus at, eleifend nibh. Cras tempus velit risus, quis rhoncus nibh viverra vel. Donec ut vulputate purus. Donec at nisl orci. Duis pellentesque vehicula dapibus. Sed in dui velit. Sed auctor pellentesque tristique. Donec vehicula ex sit amet sodales sodales. Vivamus commodo tellus sit amet lectus elementum consequat a quis quam. Aliquam erat volutpat.

Sed vestibulum nibh vel lorem varius mattis. Suspendisse rhoncus at ante in mattis. In hac habitasse platea dictumst. Nullam efficitur nisl id ex congue feugiat. In faucibus orci eu sapien feugiat, at sagittis ex condimentum. Vivamus iaculis, sapien eget bibendum laoreet, odio augue venenatis quam, non mollis nunc lectus eget massa. Praesent fermentum metus sed velit bibendum mattis. Aenean pharetra molestie urna, sed accumsan est luctus in. Donec a mi nulla. Sed vehicula semper lorem, nec rutrum orci bibendum id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam eleifend leo vitae sapien auctor tempor in in velit. Cras a velit et sapien cursus feugiat.

Sed euismod felis eu leo varius ultricies. Vivamus a elit nisl. Maecenas quis sem odio. Ut molestie diam ut urna maximus, id aliquet magna rutrum. Curabitur efficitur consectetur feugiat. Mauris et nisl nulla. Cras bibendum mollis est et imperdiet. Ut ante sapien, gravida sit amet maximus id, gravida eget metus.

Nulla ultricies non nisi ac volutpat. Duis ut hendrerit magna, ac tempus libero. Etiam molestie ligula nec lorem finibus interdum. Nullam et sem tellus. Phasellus sed sapien at tortor imperdiet tristique. Suspendisse sit amet nibh nec mauris iaculis vulputate. Suspendisse dictum hendrerit lacus eget varius. Suspendisse dui velit, malesuada at maximus eu, tempor in augue. Nam in ullamcorper enim. Donec id ullamcorper massa. Pellentesque interdum nisi vel turpis cursus pharetra. Quisque viverra, massa ut rhoncus venenatis, elit nisi gravida justo, a sodales mi justo at elit. Nulla pulvinar justo in risus tempus, quis placerat urna scelerisque. Aenean eget tempor dui, a laoreet magna.

Praesent semper nisi pharetra molestie congue. Nunc lacus justo, faucibus eu sodales eu, bibendum sit amet mi. Mauris sem risus, tempor vitae venenatis quis, congue ut nunc. Etiam faucibus dolor diam, vitae faucibus ligula convallis sit amet. Nulla id tortor nulla. Vivamus condimentum tellus nec erat lacinia, vel pulvinar nulla tincidunt. Ut justo libero, fermentum sed mollis eget, fringilla quis mauris. Donec varius blandit tortor, in egestas purus luctus ut. Aliquam consequat tincidunt tristique. Aliquam malesuada sapien ligula, eget eleifend ante eleifend vitae. Duis quis risus dui.

Donec ultrices mattis varius. Morbi vestibulum elementum rhoncus. Ut pulvinar aliquam luctus. Aliquam vel augue consequat nisl semper aliquet. Suspendisse vitae maximus ex, vel sodales felis. Morbi aliquet porttitor nisi, quis tempus nulla porta at. Nullam euismod euismod ornare. Sed finibus neque nisi, id consectetur nisl ornare commodo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris efficitur pellentesque ante ut porta. Suspendisse maximus velit eget ullamcorper consectetur. Pellentesque vitae quam eu nulla porttitor aliquam laoreet non lacus. Cras iaculis in diam quis posuere. Proin libero ante, iaculis congue lectus sit amet, viverra tristique orci.

Proin convallis erat non sem sollicitudin scelerisque. Aliquam elementum sapien in massa interdum fermentum. Maecenas ac velit felis. Suspendisse ac pretium risus, in iaculis odio. Fusce vitae sapien justo. Donec odio augue, aliquam eu lacus a, euismod facilisis erat. Sed congue aliquet malesuada. Aenean leo mauris, varius in semper in, fringilla quis turpis. Nam commodo sit amet nisl eu bibendum.

Nullam molestie at enim ac congue. Donec mattis risus in lobortis aliquet. Cras eu orci tincidunt, facilisis felis sit amet, faucibus mauris. Curabitur ut neque dui. Donec hendrerit lectus et ligula gravida sodales. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi consequat sapien eu lacus accumsan auctor. Donec quis risus in risus tempor interdum. In quis purus eu erat elementum vulputate nec et erat. Etiam elit dui, congue quis elementum dictum, imperdiet ullamcorper neque. Nam nulla augue, semper nec mi sed, sodales lacinia eros. Sed porta nulla ac metus efficitur, at sagittis massa aliquet. Proin rutrum felis eget enim condimentum sagittis. Duis efficitur, turpis sed sodales fringilla, turpis ante molestie tellus, aliquet bibendum eros magna ut massa.

Sed mattis sem tristique malesuada dapibus. Donec diam nisi, ullamcorper vitae nibh eu, auctor laoreet leo. Praesent id ligula non ante aliquam pulvinar. Nullam quis interdum sapien. Duis non enim mi. Etiam quis nisi neque. Duis fermentum aliquet eros sed interdum. Aliquam lorem lorem, bibendum et sem ut, posuere tincidunt diam.

Etiam eu hendrerit diam. Nunc bibendum magna felis, ac vulputate lectus sollicitudin nec. Vivamus laoreet enim risus, sit amet pulvinar mauris finibus laoreet. Aenean eu ipsum cursus, interdum leo non, venenatis neque. Aenean dui nibh, maximus nec ex et, placerat rhoncus massa. Vestibulum ultrices dolor vel magna vestibulum, at feugiat mauris posuere. Nulla cursus enim eu vulputate convallis. Sed hendrerit, lorem vel molestie ullamcorper, justo sapien suscipit ipsum, nec malesuada dui metus eget orci. Vestibulum varius nec libero et rhoncus. Suspendisse posuere fringilla leo at tempus. Mauris eget faucibus felis. Vivamus cursus mattis libero sit amet faucibus. Integer at mi augue. Pellentesque scelerisque lorem ultricies porta luctus.

Pellentesque tincidunt sem a porta feugiat. Proin elementum justo in nisl ullamcorper, sit amet dignissim ex malesuada. Morbi ultrices euismod auctor. Etiam vel velit malesuada, cursus ante et, posuere metus. Etiam pulvinar ex urna, vitae auctor est euismod vitae. Phasellus tincidunt egestas lorem a porttitor. Ut sodales at lacus a scelerisque. Morbi aliquet ante efficitur, elementum ex quis, lobortis magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus non velit vitae ex ultrices vulputate sed quis ante. Quisque placerat consectetur purus id convallis.

Mauris auctor tempor massa sit amet condimentum. Etiam sollicitudin et lorem tempus maximus. Maecenas id tincidunt mauris. Donec rhoncus ex nisi, quis lobortis enim porta vel. Nullam sed augue vel nisl feugiat feugiat. Curabitur nec sapien in ex interdum aliquet a quis risus. Vestibulum luctus, neque a elementum tristique, turpis nunc aliquam sem, id ullamcorper nisi turpis a mauris. Nam risus lectus, tempus at sapien et, condimentum mattis nisi. Curabitur commodo ex felis, non aliquam nibh euismod id. Phasellus eget feugiat ipsum, non lacinia purus.

Ut feugiat, sem vel scelerisque volutpat, ipsum sapien suscipit nunc, feugiat ultrices nunc diam ac lectus. Duis vitae ante eget sem cursus interdum. Phasellus dignissim elementum semper. Donec pharetra diam sit amet lacus imperdiet, vel pretium dolor pellentesque. Sed dictum sollicitudin fringilla. Vestibulum ut tortor sodales risus interdum congue sed a nisl. Fusce sit amet egestas mi. Nulla lacinia, dolor non blandit tristique, quam velit iaculis ante, sit amet faucibus augue elit in dui. Suspendisse vulputate consectetur justo quis vulputate.

Nam eu purus purus. Morbi eu varius dolor. Suspendisse quis ex sed dolor eleifend hendrerit sed et eros. Phasellus eget elementum erat. Ut sit amet ullamcorper nisl, non ullamcorper augue. Phasellus semper ex quis laoreet tincidunt. Nulla ac vestibulum magna. Donec consequat justo eget risus sagittis lacinia. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut vel convallis tellus, nec porta tellus. Ut volutpat ipsum nec iaculis dictum.

Donec semper libero augue, ac dictum nibh faucibus vel. Nulla imperdiet purus vitae fermentum finibus. Fusce cursus lacus nec felis consectetur consequat. Sed auctor blandit lorem ac pretium. Pellentesque porttitor venenatis vehicula. Duis vel tellus nec lorem egestas gravida nec non felis. Pellentesque fermentum dolor ac nisi placerat, in suscipit orci consectetur. Sed mattis lorem eget sem bibendum volutpat dignissim at augue. Aliquam et nibh ligula. Duis ut ex nec nunc placerat hendrerit.

Vestibulum auctor, lectus a vestibulum tempus, elit mauris blandit dolor, lacinia porta erat sem id massa. Etiam at quam vel massa volutpat euismod. In a gravida orci. Aliquam condimentum libero sed condimentum accumsan. Quisque porttitor ac tortor eu vestibulum. Mauris sagittis, enim quis tristique mollis, nulla sem maximus est, sed suscipit quam sem nec felis. Nullam pellentesque erat in magna molestie, quis efficitur nibh porta. Sed tempus blandit risus et efficitur. Praesent interdum aliquet luctus. Etiam sollicitudin pellentesque enim, vitae porttitor leo vulputate eu. Morbi vel turpis ac tortor condimentum vulputate eget vel mi. Aliquam et magna leo. Vivamus vitae facilisis tortor.

Sed semper, enim eget congue malesuada, lorem ex varius odio, sit amet congue libero odio suscipit nunc. Maecenas consectetur leo quis neque facilisis pellentesque. Vestibulum quis nisi eget leo convallis vulputate. Suspendisse convallis dapibus placerat. Vestibulum in viverra purus, in cursus purus. Donec id risus scelerisque, semper nisi id, ultricies ligula. Cras egestas tortor quis egestas tempus. Phasellus interdum suscipit rhoncus.

Curabitur vel quam sapien. Aliquam luctus, est non dapibus luctus, metus dolor pharetra neque, at facilisis dolor nibh id mi. Mauris vestibulum iaculis nibh ut accumsan. Quisque mollis tincidunt euismod. Nam ligula enim, molestie vitae nulla ut, dignissim semper quam. Duis iaculis eros id lacus vestibulum tempor. Ut vitae posuere ligula. Nunc elit tellus, rhoncus ut viverra quis, semper nec urna. Sed ipsum ligula, viverra rhoncus leo at, tempor aliquam risus.

In malesuada, augue ac sodales congue, sapien lorem aliquam nunc, et tempus nisi nulla ut purus. Mauris eu orci in risus efficitur suscipit. Mauris semper condimentum nisl, sed blandit velit. Sed sed imperdiet augue. Nunc consectetur euismod magna, sit amet ultricies quam viverra sed. Aliquam malesuada nec mauris vel tristique. Proin est ipsum, commodo ac felis in, molestie aliquam ex.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris commodo, enim at ullamcorper lacinia, ante mi posuere lacus, quis eleifend metus nisi sit amet ligula. Donec urna sem, porta in rhoncus vitae, maximus eget lacus. Vestibulum commodo ligula quis quam bibendum hendrerit. Curabitur ornare libero mauris, ac lobortis tortor commodo vestibulum. Etiam libero felis, varius eget pretium ut, accumsan nec tortor. Donec in enim ac sem aliquet egestas nec consectetur libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi ac enim non quam finibus sollicitudin quis et turpis. Integer ut risus felis. Morbi euismod sapien laoreet metus vulputate semper. Morbi eu augue consequat, ultricies diam a, sollicitudin nisl. Quisque non laoreet lectus.

Integer a turpis orci. Maecenas id vestibulum metus, ac dignissim est. Vivamus ut mi neque. Suspendisse in turpis cursus, varius dolor pellentesque, euismod tortor. Cras quis pellentesque quam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer aliquet, urna in accumsan fringilla, neque purus ultrices enim, sit amet ultrices nunc erat nec velit. Duis ut commodo sem.

Quisque blandit justo purus, at porta turpis auctor in. Mauris eu ante sagittis, tristique ante ut, consequat lacus. Nunc vehicula a nisl id mattis. Suspendisse iaculis orci quis odio sodales iaculis eget elementum est. Curabitur porttitor tortor at lorem feugiat euismod. Quisque facilisis diam et lectus viverra, quis luctus dui blandit. Praesent commodo lectus at eros rhoncus, quis pulvinar sapien blandit. Sed sed ornare nulla, vitae placerat lacus.

Suspendisse eget augue lobortis, porttitor tortor vitae, posuere nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis iaculis, justo nec posuere lacinia, orci leo convallis mi, eu sodales libero eros non massa. Phasellus ornare blandit sodales. In fringilla enim pulvinar sagittis malesuada. Phasellus rhoncus pharetra lorem, rutrum ornare justo ornare id. Nullam sagittis suscipit orci fringilla dictum. Aenean pellentesque justo non neque consequat, nec auctor libero aliquam. Integer leo enim, interdum aliquet mattis vitae, malesuada sed tortor. Duis et eleifend quam. Aenean luctus tempus nisl, eget vestibulum dui hendrerit vitae. Aenean venenatis erat nulla, a maximus nisi faucibus eget. Praesent congue aliquam nisi, id blandit velit eleifend a. In facilisis sagittis magna eget gravida. Aenean in cursus diam. Vestibulum ultricies quis nunc in tristique.

Quisque molestie dictum enim non egestas. Quisque tincidunt eu nunc eu pulvinar. Aenean ut tellus condimentum, gravida nisl sed, fermentum purus. Vivamus at neque eu mi laoreet ultricies eu a nisl. Integer tincidunt mi est, at porta lacus interdum in. Sed massa libero, consequat eu nunc sed, malesuada scelerisque urna. Sed pellentesque felis nibh, a sagittis diam consectetur et. Fusce vel quam nec tortor finibus varius at a quam.

Etiam aliquam nisl sem, eget blandit lorem feugiat in. Aenean tristique sapien consectetur nulla ullamcorper lacinia ut nec magna. Quisque eu nisi interdum, dapibus felis non, scelerisque mauris. Maecenas dapibus, elit vitae tempus convallis, arcu est sodales urna, rhoncus euismod lorem elit fermentum enim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Donec vitae elementum odio, eget euismod sapien. Mauris quis ligula sem. Curabitur convallis fringilla urna, a volutpat purus lobortis vitae. Nam maximus mi vel ornare tempor. Donec ac ipsum id nulla malesuada molestie. Aenean finibus elit nec facilisis maximus. Cras nec euismod nulla. Nulla non risus ut tellus luctus convallis vitae vitae diam. Nulla elit nisl, elementum vel sodales in, varius nec lorem.

Phasellus molestie blandit enim ornare dignissim. Aenean dictum, ipsum feugiat posuere sagittis, enim urna mollis turpis, in ultrices lacus nisi at mauris. Vivamus faucibus finibus diam at elementum. Aenean eget felis et turpis fermentum rutrum porttitor a dolor. Vestibulum feugiat, ante at luctus ultrices, enim ligula consequat ipsum, id facilisis est sem non lacus. Etiam ornare tortor risus, at congue arcu tincidunt vitae. Phasellus id molestie ipsum. Pellentesque in ligula convallis, gravida orci ac, faucibus risus. Nam aliquet imperdiet blandit. Cras a faucibus urna. Maecenas ligula quam, posuere vitae augue vitae, tempor tempus mauris. In interdum cursus nibh vitae semper. Integer imperdiet, nulla quis molestie vulputate, velit dui pretium ipsum, et feugiat nisi enim quis mi. Nulla laoreet rhoncus purus eget ornare.

Aenean felis dolor, scelerisque eget neque nec, pharetra ornare nisl. Etiam mollis nec quam eget dapibus. Sed ut porta arcu. Aliquam leo odio, mattis quis eleifend ac, aliquam id nibh. Ut eu tristique felis, vel dignissim sapien. Quisque non ligula sodales, condimentum diam at, blandit massa. Phasellus pharetra, purus id venenatis malesuada, eros orci aliquam justo, sed tristique ligula nulla vitae mauris. Vestibulum vitae volutpat mauris.

Maecenas vehicula faucibus leo eget auctor. Mauris fermentum velit at accumsan tincidunt. Praesent lobortis dolor at elit cursus, condimentum euismod metus venenatis. Praesent eu risus in felis mattis sollicitudin. Curabitur lobortis hendrerit ex, eget pulvinar velit pharetra nec. Aliquam maximus purus a libero laoreet, eu dictum dolor dignissim. Praesent nunc urna, blandit eget libero sit amet, placerat elementum metus. Donec egestas, lorem vel condimentum feugiat, tortor massa interdum sem, sed ullamcorper orci risus eget purus. Maecenas cursus sagittis ipsum sit amet sollicitudin. Cras at ligula eget purus tristique elementum. Nullam accumsan, ex sed vestibulum efficitur, lorem nisi condimentum diam, nec accumsan sapien ligula ac leo.

Integer scelerisque, lacus sed auctor sollicitudin, quam nibh bibendum purus, in posuere turpis urna a nunc. Nulla eu nisl eu metus tempus luctus in in dui. Nulla porttitor vehicula velit. Aenean id nisi sed erat lobortis congue non a mi. Praesent ultricies laoreet tortor in placerat. Mauris condimentum non urna vel tristique. Maecenas vehicula tellus id elementum porttitor. Donec hendrerit, magna ac commodo eleifend, libero nulla pretium orci, quis porta orci nulla eu nulla. Donec consequat sapien ut arcu sodales, ac laoreet lectus dictum. Proin non turpis quis nunc gravida malesuada lacinia a risus. Duis porttitor erat a diam dictum, gravida efficitur nisi mollis. Aliquam rutrum tortor ullamcorper, feugiat lectus vitae, rhoncus risus. Quisque enim est, tempus a purus feugiat, laoreet commodo dui. Mauris sollicitudin velit sit amet facilisis ultrices. Vivamus gravida est nunc, id efficitur arcu vestibulum sed. Cras at est mollis, suscipit velit eget, fermentum urna.

Phasellus euismod felis ut tortor dignissim, eget lacinia enim elementum. Fusce suscipit ultricies lacus in consectetur. Ut congue pellentesque enim ut porttitor. Sed ac urna tortor. Vestibulum euismod diam vel libero condimentum efficitur. Pellentesque mollis lectus vitae ante ultrices mattis. Maecenas tortor risus, viverra scelerisque finibus a, rhoncus quis dolor. Quisque id velit suscipit, auctor massa nec, efficitur ipsum. Nulla condimentum feugiat sapien, sit amet sagittis augue fringilla vel. Vivamus facilisis fringilla bibendum. Duis viverra, libero volutpat finibus placerat, nisl elit tincidunt metus, sit amet suscipit sapien mi vitae neque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut vel aliquet nulla.

Morbi ac eros tristique magna ullamcorper fermentum. Donec lectus mauris, rutrum sed malesuada vitae, vulputate vel velit. Aliquam ante arcu, mollis a interdum vitae, tincidunt eget diam. Etiam congue, magna porttitor laoreet egestas, elit eros vehicula ipsum, quis volutpat mi turpis non mauris. Integer bibendum euismod lorem. Nullam euismod massa a turpis efficitur, tristique molestie nisi bibendum. Mauris augue nunc, varius nec cursus et, dignissim a risus. Nulla sed orci non orci eleifend finibus. Quisque mattis interdum nisi et cursus. Proin rutrum condimentum lorem, at tristique ligula fermentum vitae. Nam feugiat, neque sed bibendum faucibus, purus lectus fringilla dui, ut maximus urna nunc iaculis velit. Vivamus ultrices turpis quis dapibus porttitor.

Ut tortor felis, dignissim placerat vulputate quis, luctus in sem. Etiam ac efficitur arcu. Fusce dapibus, purus eget fringilla pulvinar, massa massa hendrerit risus, sed hendrerit diam erat in odio. Suspendisse a finibus ligula. Fusce volutpat finibus lectus ac sagittis. Donec auctor porttitor metus, ut pretium ante sodales eu. Duis eu rutrum diam. Donec ullamcorper interdum erat eget molestie. Curabitur felis est, pharetra sed consequat in, sollicitudin ut eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam a vehicula dolor. Pellentesque leo ex, efficitur eu aliquam sed, molestie vel nisi.

Phasellus vehicula dictum mauris, in pulvinar turpis egestas a. Praesent maximus odio malesuada nunc semper, et pulvinar neque pharetra. Etiam ullamcorper porttitor porttitor. Morbi rutrum iaculis odio, et venenatis erat varius sit amet. In scelerisque mauris quis purus imperdiet hendrerit. Aenean accumsan turpis turpis, nec accumsan eros gravida ut. Mauris sit amet efficitur sem, ut sagittis mauris. Sed non massa vel ligula condimentum varius eu in erat.

In fermentum molestie felis. Sed viverra ut mauris vitae scelerisque. Ut eget nibh ex. Donec vitae euismod justo, sed elementum libero. Suspendisse nec erat at nunc euismod euismod eget nec orci. Etiam porttitor turpis vitae felis tempus sollicitudin. Maecenas in molestie velit. Proin ac ex non augue ultricies sodales. Nullam ac convallis dolor. Phasellus eleifend laoreet hendrerit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Aliquam congue orci non ligula vehicula, non volutpat nisi vulputate. Sed malesuada non purus id vulputate. Vivamus dignissim, odio vel sagittis egestas, nisl elit posuere ipsum, auctor vulputate erat nisi ut dui. Curabitur vitae enim vel lacus laoreet venenatis. In vulputate vulputate tristique. Suspendisse quis quam odio. Suspendisse in neque iaculis, blandit est sit amet, hendrerit metus. Quisque tempus dolor dignissim ligula tristique lacinia. Cras malesuada commodo metus nec aliquam. Phasellus elementum aliquam congue. Vestibulum pharetra at augue eget rhoncus. Aliquam in molestie ligula, eu gravida nunc. Nam sed nulla in urna dapibus mattis at quis velit. Nulla vel consectetur elit, non sodales diam.

Proin tincidunt efficitur lorem, id molestie nulla sodales ac. Praesent at ante tristique, elementum quam vitae, mattis sapien. Curabitur mollis metus orci, non rutrum felis consequat nec. Mauris vel turpis in felis mattis pretium. Fusce dictum magna sem, eu efficitur ligula maximus a. Quisque sagittis felis nisl, vitae vehicula libero tempus ut. Sed blandit in purus eget aliquam. Maecenas a vehicula eros. Morbi ultrices sem sed nulla luctus, ut interdum nisl condimentum. Nunc ac lectus dolor.

Vivamus ac dui nunc. Vivamus pharetra risus augue, sit amet feugiat elit ultricies eu. Praesent rutrum massa sodales bibendum ullamcorper. Vestibulum ante nibh, fermentum ut ullamcorper id, bibendum vitae ex. Quisque non risus in odio laoreet lobortis. Proin lacinia, quam vel aliquam consequat, turpis purus elementum massa, at vulputate sapien enim eget tortor. Nullam volutpat quis metus ut varius. Nunc nec elit at elit ultricies lobortis quis efficitur mauris. In euismod turpis viverra eros dignissim sollicitudin. Fusce tincidunt, metus eget finibus ultricies, lacus dui rutrum magna, pellentesque laoreet diam ex ut urna.

Ut ac faucibus lacus, in luctus mauris. Integer sagittis, tortor ut faucibus tempor, massa lectus posuere ligula, sed ullamcorper risus ligula vitae est. Curabitur id mollis enim. Nulla facilisi. Vestibulum et neque pellentesque, dictum arcu eu, sagittis lectus. Integer pulvinar mauris nec mi pretium, eget rhoncus lorem auctor. Quisque sagittis augue sed tellus finibus, sit amet hendrerit felis consequat.

'''

from random_word import RandomWords
import random
r = RandomWords()
smapl_len = len(sample)
# Return a single random word
for number in range(250):
    word = r.get_random_word()
    des = ''
    start_desc = random.randrange(smapl_len)
    end_desc = random.randrange(100)
    if start_desc + end_desc > smapl_len:
        start_desc -= 200
    des = sample[start_desc:start_desc+end_desc+1]
    local_addres = end_desc
    endpoint = "http://127.0.0.1:8000/api/add/local/"
    data = {
        'name':word,
        'description':des,
        'local_addres':end_desc,
    }
    get_respone = requests.post(endpoint, json=data)
    print(get_respone.json())