# Generated by Django 4.1.4 on 2023-01-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='messages',
            field=models.ManyToManyField(to='message.messagesroom'),
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='messages_room_ask',
            field=models.ManyToManyField(to='message.roomdeleteask'),
        ),
    ]
