# Generated by Django 4.1.4 on 2023-01-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotifications',
            options={'get_latest_by': 'added'},
        ),
    ]
