# Generated by Django 4.1.4 on 2023-01-17 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usernotifications_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
