# Generated by Django 4.1.4 on 2023-01-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(to='message.messagesroom')),
                ('messages_room_ask', models.ManyToManyField(to='message.roomdeleteask')),
            ],
        ),
    ]
