# Generated by Django 4.1.4 on 2023-01-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='posts',
            field=models.ManyToManyField(to='posts.post'),
        ),
    ]
